### ISSUE TITLE
react-google-maps

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#14]
## Value statement - a requirement, not a solution
As a **user** 
I need **a google map** 
so that **i can see, where the Office is**

## Acceptance criteria
- [ ] move around in map
- [ ] click on map, redirect to google

## Tasks
- [ ] (todos for the team)

## Size
(small)

**Comment by mpagels** [comment]
Closes. Map ist eingebunden.
