### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#20]
## Value statement - a requirement, not a solution
As a **user** 
I need **a contact Form** 
so that **I can send important information to the doctor** 

## Description (Text, Scribble, Wireframe, Design)

![Bildschirmfoto 2020-11-17 um 14 12 43 Kopie](https://user-images.githubusercontent.com/54703643/99394661-89d22200-28df-11eb-909f-c6cf2c368a63.png)

## Acceptance criteria
- [x] when click "Nachricht abschicken", the form disappear and a message is shown "message send"
- [x] the input fields shown placehholder texts
- [x] show if input is wrong (input validation)
- [x] send contact infos through emailJS to info@nordlichter-halstenbek.de

## Tasks
- [x] (todos for the team)

## Size
(large)
