### ISSUE TITLE
Add "write another email" email after email was send

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#27]
## Value statement - a requirement, not a solution
As an **user** 
I need **the possibilty to write another email, after the last one was send** 
so that **I can write a another email without reload the page** 

## Acceptance criteria
- [ ] after the email was send, I can click the button "Eine weitere Email schreiben"
- [ ] the little "was send" symboly disappear and the form comes back empty
- [ ] I can write a another email and can send it
- [ ] after successfully send, the "was send" symbol comes back and the forms disappear
- [ ] after the email was send, I can click the button "Eine weitere Email schreiben"

## Tasks
- [ ] (todos for the team)

## Size
(smal)
