### ISSUE TITLE
Mobil NavBar

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#5]
## Value statement - a requirement, not a solution
As a **user** 
I need **a NavBar at the top of the website** 
so that **I can navigate through the website**
## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/54703643/99130154-d7187000-260f-11eb-90cf-cd3dc54f201e.png)  

![grafik](https://user-images.githubusercontent.com/54703643/99130140-cd8f0800-260f-11eb-8751-2040ca9565a0.png)

## Acceptance criteria
- [x] sticky on top of the page
- [x] shows current "location" as headline of website
- [x] at the right, there is a mail symbol which links to the contact site on click
- [x]  when click on the "burger" menu, the navigation opens and show all other navigation links
- [x]  when click on one of them, the nav menu closes and the page navigates to the site

- [x] when click on the burger menu, it animates to an open symbol
- [x] when close it shows the typical burger menu symbol

## Tasks
- [x] create api js for the navlinks
- [x]  create navBar component

## Size
(large)
