### ISSUE TITLE
Universal Site Footer

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#6]
## Value statement - a requirement, not a solution
As a **user** 
I need **a footer** 
so that **I can show all important information at the bottom at the page** 

## Description (Text, Scribble, Wireframe, Design)
![grafik](https://user-images.githubusercontent.com/54703643/99130605-172c2280-2611-11eb-8c53-47dfac1d64b8.png)

## Acceptance criteria
- [x] shows "Sprechzeiten"
- [x] shows "Kontakt"
- [x] when click on email then it opens the mail programm of the user
- [x] shows "Facebook"
- [x]  when click on facebook sign, it redirects to facebook site
- [x] shows "Impressum"
- [x] shows "Map" from the office location 
- [x] on click google maps opens in route mode

## Tasks
- [x] create api for footer informatioen
- [x]  create component
- [x] research google map component

## Size
(medium)
